repos:
  - repo: local
    hooks:
      - id: swift-format
        name: Swift Format
        entry: swift format --in-place
        language: system
        files: \.swift$
        pass_filenames: true

      - id: swift-files-in-project
        name: Check Swift files in Xcode project
        entry: scripts/check-swift-files-in-project.sh
        language: script
        files: \.swift$
        pass_filenames: false
